/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'ssl_client1.Debug+IMXRT1050-EVKB' 
 * Target:  'Debug+IMXRT1050-EVKB' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "fsl_device_registers.h"

/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* ARM::Security:mbed TLS@3.6.4 */
#define RTE_Security_mbedTLS            /* Security mbed TLS */
/* Keil::CMSIS Driver:Ethernet MAC@1.6.0 */
#define RTE_Drivers_ETH_MAC0    (1U)    /* Driver ETH_MAC0 */
/* Keil::CMSIS Driver:Ethernet PHY:KSZ8081RNA@6.3.0 */
#define RTE_Drivers_PHY_KSZ8081RNA      /* Driver PHY KSZ8081RNA/RND */
/* Keil::CMSIS Driver:MCI@1.5.0 */
#define RTE_Drivers_MCI0        (1U)    /* Driver MCI0 */
#define RTE_Drivers_MCI1        (1U)    /* Driver MCI1 */
/* Keil::CMSIS Driver:VIO:Board&IMXRT1050-EVKB@2.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_IMXRT1050_EVKB
/* Keil::Network&MDK:CORE@8.1.0 */
#define RTE_Network_Core                /* Network Core */
/* Keil::Network&MDK:Interface:ETH@8.1.0 */
#define RTE_Network_Interface_ETH_0     /* Network Interface ETH 0 */

/* Keil::Network&MDK:Service:DNS Client@8.1.0 */
#define RTE_Network_DNS_Client          /* Network DNS Client */
/* Keil::Network&MDK:Socket:BSD@8.1.0 */
#define RTE_Network_Socket_BSD          /* Network Socket BSD */
/* Keil::Network&MDK:Socket:TCP@8.1.0 */
#define RTE_Network_Socket_TCP          /* Network Socket TCP */
/* Keil::Network&MDK:Socket:UDP@8.1.0 */
#define RTE_Network_Socket_UDP          /* Network Socket UDP */
/* NXP::Board Support:SDK Project Template:project_template&evkbimxrt1050@1.0.0 */
#ifndef XIP_EXTERNAL_FLASH
#define XIP_EXTERNAL_FLASH 1
#endif
#ifndef XIP_BOOT_HEADER_ENABLE
#define XIP_BOOT_HEADER_ENABLE 1
#endif
/* NXP::Device:SDK Drivers:codec@2.3.1 */
#ifndef SDK_I2C_BASED_COMPONENT_USED
#define SDK_I2C_BASED_COMPONENT_USED 1
#endif
/* NXP::Device:SDK Drivers:codec_i2c@2.1.0 */
#ifndef SDK_I2C_BASED_COMPONENT_USED
#define SDK_I2C_BASED_COMPONENT_USED 1
#endif
/* NXP::Device:SDK Drivers:wm8960@2.2.2 */
#ifndef SDK_I2C_BASED_COMPONENT_USED
#define SDK_I2C_BASED_COMPONENT_USED 1
#endif
#ifndef BOARD_USE_CODEC
#define BOARD_USE_CODEC 1
#endif
#ifndef CODEC_WM8960_ENABLE
#define CODEC_WM8960_ENABLE 
#endif
/* NXP::Device:SDK Utilities:serial_manager_uart@1.0.0 */
#ifndef SERIAL_PORT_TYPE_UART
#define SERIAL_PORT_TYPE_UART 1
#endif


#endif /* RTE_COMPONENTS_H */
